language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

# command to install dependencies
install: "python setup.py develop"

# command to run tests
script: "python setup.py test"
